repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    - id: isort
      args: ["--profile", "black"]

-   repo: https://github.com/python/black
    rev: 21.5b2
    hooks:
    - id: black

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.19.3
    hooks:
    - id: pyupgrade
      args: ["--py39-plus"]
