name: Orcasound processing

on:
  # To run manually
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -U setuptools wheel
        python -m pip install awscli matplotlib scipy

    # - name: Get latest timestamp
    #   run: |
    #     aws --no-sign-request s3 cp s3://streaming-orcasound-net/rpi_bush_point/latest.txt .
    #     read -r timestamp<latest.txt
    #     echo "timestamp=$timestamp" >> $GITHUB_ENV

    - name: Set hardcoded "full" timestamp
      # 1618317018
      # Tue Apr 13 2021 12:30:18 GMT+0000
      run: |
        echo "timestamp=1618317018" >> $GITHUB_ENV

    - uses: actions/cache@v2
      id: cache
      with:
        path: |
          bush_point/${{ env.timestamp }}/
        key: bush_point-${{ env.timestamp }}

    - name: Get all files
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        aws --no-sign-request s3 sync s3://streaming-orcasound-net/rpi_bush_point/hls/${{ env.timestamp }}/ bush_point/${{ env.timestamp }}

    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg

    - name: Concat all files into one just for fun
      run: |
        ffmpeg -f concat -safe 0 -i <(for f in bush_point/${{ env.timestamp }}/*.ts; do echo "file '$PWD/$f'"; done) -c copy all.wav

    - name: Upload combined wav file
      uses: actions/upload-artifact@v2
      with:
        name: all.wav
        path: all.wav

    - name: Convert all files to .wav
      run: |
        mkdir -p wav/bush_point/${{ env.timestamp }}
        for file in bush_point/${{ env.timestamp }}/*.ts; do ffmpeg -i "$file" "wav/${file%.*}.wav"; done
    
    - name: Create spectrograms
      run: |
        mkdir -p png/bush_point/${{ env.timestamp }}
        python orcasound_processing.py wav/bush_point/${{ env.timestamp }} -o png/bush_point/${{ env.timestamp }}

    - name: Upload spectrograms
      uses: actions/upload-artifact@v2
      with:
        name: Spectrograms
        path: |
          png/bush_point/${{ env.timestamp }}/*.png
