name: Orcasound processing

on:
  # To run manually
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -U setuptools wheel
        python -m pip install awscli

    - name: Get latest timestamp
      run: |
        aws --no-sign-request s3 cp s3://streaming-orcasound-net/rpi_bush_point/latest.txt .
        read -r timestamp<latest.txt
        echo "timestamp=$timestamp" >> $GITHUB_ENV
    - name: Echo timestamp
      run: |
        echo "${{ env.timestamp }}"
