name: 

on:
  # To run manually
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2

    - name: Install Python dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -U setuptools wheel
        python -m pip install awscli matplotlib scipy m3u8 git+https://github.com/kkroening/ffmpeg-python
    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg

    - name: Hello world 
      run: |
        python -m "import scipy as sp; print('Scipy's version'+sp.__version__)"
        python -m "import matplotlib as mpl; print('Matplotlib's version'+mpl.__version__)"
        



   


